let metinler = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed dui turpis. Vivamus eu libero nunc. Vivamus lacinia dui quis urna porttitor gravida. Suspendisse in lorem ac metus dignissim ornare a non est. Duis non arcu turpis. Proin auctor tempus lectus nec rhoncus. Mauris sed consectetur mauris. Phasellus sapien metus, tempor vel lorem eget, dapibus consequat neque. Quisque nec finibus dui. Quisque auctor turpis ac finibus interdum. Aliquam mollis nibh id odio fermentum vulputate. Sed nec suscipit ligula. Nunc feugiat lacinia nunc et iaculis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec pharetra nunc vitae ipsum bibendum, at efficitur massa semper. Nulla facilisi.",
  "Phasellus cursus eros vitae ex dignissim, a eleifend diam cursus. Cras eget nisl vitae velit luctus faucibus. Mauris a viverra neque, sit amet pellentesque nibh. Proin at sapien a purus luctus fermentum quis id urna. Curabitur enim tellus, tristique sit amet tellus ac, suscipit pulvinar nulla. Cras quis pretium lacus. Fusce nec varius ligula. In hac habitasse platea dictumst. Duis vel feugiat orci. Cras tempor vulputate consectetur. Vivamus laoreet posuere neque non maximus. Praesent tincidunt sed nisl at aliquam. Etiam ex tellus, ornare vitae sollicitudin sed, pulvinar non erat.",
  "Aliquam elit elit, fringilla rhoncus arcu et, pellentesque bibendum leo. Morbi ultrices sit amet sapien a condimentum. Aliquam erat volutpat. Proin ornare erat ex, lobortis placerat enim laoreet in. Sed dignissim viverra luctus. Vestibulum ultrices lacus ex, ac tristique dolor mattis vel. Nam in lorem leo. Nullam dictum ex ut metus consequat, a maximus nisi tempus. Quisque semper erat at ipsum blandit eleifend. Duis luctus feugiat lectus, eu scelerisque quam convallis fringilla. Pellentesque congue iaculis ultrices. Praesent suscipit urna lectus, a blandit tellus facilisis ut. Nulla semper ullamcorper leo a euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer sollicitudin placerat vulputate. Pellentesque tincidunt nisi porta, rutrum augue sed, ornare dolor.",
  "Etiam eu sagittis nulla. Nulla ultrices pellentesque arcu, vel tincidunt nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi eleifend porta neque, vel porta enim. Cras aliquet est euismod, dictum turpis in, blandit mauris. Mauris pellentesque quam dolor, non consequat nibh elementum id. Nullam metus sem, pulvinar in sagittis vitae, vestibulum id sapien. Curabitur accumsan at massa non sagittis. Vestibulum vitae justo finibus, hendrerit orci at, eleifend tortor. Curabitur consequat, libero vel rhoncus dignissim, quam elit blandit elit, non auctor ex magna id libero. Ut magna nisl, convallis nec tortor a, lacinia dapibus lacus. Nulla a urna nec diam posuere laoreet. Aenean facilisis velit sed orci sollicitudin mattis.",
  "Cras eu augue pretium nunc consequat maximus. Vivamus varius ante id sodales efficitur. Quisque iaculis ex in efficitur lobortis. Morbi auctor lacus a sollicitudin commodo. Cras vel suscipit libero. Fusce accumsan vestibulum efficitur. Mauris volutpat arcu eu arcu egestas, a consectetur felis dapibus. Vivamus a blandit nibh, luctus consequat libero. Vestibulum ac efficitur libero. Nunc consequat libero nec viverra tincidunt. Vestibulum ultricies, turpis eu fringilla venenatis, urna sapien sodales urna, nec mollis eros metus at mi. Donec interdum lacus ut blandit accumsan. Donec at velit libero. Curabitur in interdum leo, quis hendrerit diam.",
  "Duis sit amet neque et purus porta venenatis sit amet sed est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ut justo et orci dictum tincidunt. Aliquam erat volutpat. Aliquam placerat tincidunt enim, vel rhoncus erat rutrum sit amet. Pellentesque mollis luctus odio, ac mattis lacus fermentum sit amet. Nunc elementum nisi turpis, vel auctor velit ultricies sed. Etiam luctus, tellus ut maximus fermentum, mauris odio euismod quam, vel vestibulum justo massa elementum ex.",
  "Nunc lacinia fermentum tellus ut rhoncus. Donec dignissim, neque non gravida cursus, quam urna elementum felis, ut hendrerit est libero id purus. Maecenas ac nibh vel nunc aliquam hendrerit sit amet id elit. Aenean fringilla justo sit amet nunc ultrices volutpat. Quisque vel mauris a lectus varius ornare vitae sit amet ex. Donec eget fringilla lorem. Cras elementum tortor arcu, at cursus odio sodales at. In auctor nec metus non eleifend. Nullam vel mollis arcu. Etiam vel vulputate metus. Nam vehicula, enim sit amet vulputate finibus, lorem quam venenatis libero, non blandit massa augue eu ex.",
  "Pellentesque ipsum sem, tincidunt non massa eget, faucibus cursus enim. Integer at auctor mauris. Duis ultrices nec sem a pharetra. Donec pulvinar dignissim fermentum. Donec venenatis a dolor sed commodo. Sed at orci ut turpis venenatis finibus. Praesent vel tortor risus. Suspendisse potenti. Nullam ipsum elit, consequat id pretium eu, finibus a nunc. Donec nec dolor eget eros posuere mollis quis ac purus. Fusce placerat accumsan efficitur. Nullam in sapien purus. Cras vitae orci pulvinar, hendrerit nisl quis, blandit diam. Curabitur consectetur purus eu odio pharetra tincidunt.",
  "Sed ac metus ex. Vestibulum egestas porta ullamcorper. Morbi sed accumsan ex. Pellentesque id felis et odio varius mattis sit amet vitae eros. Ut aliquet ligula diam, a fermentum nunc pulvinar eget. Morbi faucibus, lacus malesuada vestibulum consequat, turpis ipsum pulvinar tortor, non tincidunt ipsum ex sed nibh. Quisque ultrices eleifend pellentesque.",
  "Maecenas condimentum pretium mauris, ut condimentum tortor posuere vitae. Fusce vel ornare elit. Nunc in vulputate erat, eget interdum ligula. Quisque accumsan ultrices nunc et feugiat. Vestibulum pharetra imperdiet pellentesque. Fusce augue dui, luctus quis tempus eget, iaculis in felis. Etiam gravida neque vel nulla tempor efficitur. Nullam ut dignissim mi. Phasellus vel aliquet felis. Duis sodales accumsan magna, ac vehicula nisi posuere a. Nulla facilisi. Donec ultricies facilisis commodo. Praesent consectetur, diam id gravida lobortis, urna metus congue velit, ac ultrices ante nisl non arcu. Nam justo leo, interdum sit amet nibh ac, maximus imperdiet justo. Donec tempor turpis vitae ligula sagittis, eget consequat ex feugiat. In vulputate vitae ipsum at interdum.",
  "Duis sapien ipsum, bibendum consectetur felis finibus, fringilla pulvinar arcu. Etiam mattis ultricies aliquet. Nullam sit amet sodales nibh. In nisl massa, pretium vel volutpat nec, scelerisque eu felis. Etiam eget lorem eu lorem congue eleifend non in lectus. Mauris consectetur vehicula enim, vel posuere turpis viverra vitae. Nunc a rhoncus lacus. Phasellus vestibulum elit dolor, vitae feugiat nisl euismod eu. Quisque sapien velit, fringilla eget enim eget, tempus rutrum leo. Proin laoreet ante eu mi posuere fermentum. Donec nisi nunc, eleifend sed diam a, tristique placerat mauris. Vestibulum nec eros turpis. Sed interdum volutpat ante sed cursus.",
  "Maecenas arcu mauris, pulvinar sollicitudin venenatis ut, lacinia sed enim. Suspendisse ultrices vehicula quam vitae blandit. Sed varius diam vitae nisi maximus dapibus. Proin a lectus eget elit fringilla dignissim vitae id sapien. Donec mi velit, imperdiet quis sapien non, lobortis pretium sem. Maecenas dapibus malesuada consequat. Fusce sed velit aliquet nibh faucibus rutrum. Nam justo leo, malesuada vitae sollicitudin ac, pulvinar in massa. Aenean vel lacinia lacus. Integer sem mauris, volutpat et turpis ac, volutpat pretium enim. Nulla viverra vitae mi quis lobortis. Donec orci dui, aliquam vel venenatis sed, suscipit pretium risus.",
  "Sed ac justo eros. Integer id est in augue interdum posuere nec a enim. Nunc semper nibh et nunc eleifend iaculis. Praesent a porttitor tellus, id elementum urna. Mauris quis dapibus diam. Morbi interdum ipsum et magna finibus, sit amet blandit odio rutrum. Maecenas finibus magna id leo porttitor, eget imperdiet dui porttitor. Quisque pulvinar nisl non magna gravida aliquet. Curabitur quis pharetra lectus. Praesent quis fringilla nisl. Donec eu erat vel dui convallis egestas.",
  "Fusce pharetra mi dui, vel aliquam libero ornare non. Maecenas condimentum posuere consectetur. Nunc nec ultrices lacus, id elementum justo. Fusce feugiat aliquet mauris, volutpat semper felis. Duis pulvinar porta risus, sit amet venenatis lectus. Duis sed est id felis porta sollicitudin. Morbi id luctus tellus. Vivamus lobortis tempor elementum. In rhoncus libero eget tincidunt varius. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi nec arcu quis dolor vulputate luctus eget id ipsum. Nam eget dapibus ex. In dui ligula, tristique eu turpis eu, dictum gravida ante.",
  "In tempor dui ex, at imperdiet turpis facilisis placerat. In ac dolor at purus rutrum gravida eu et risus. Suspendisse pulvinar, ante vitae maximus semper, urna lectus suscipit est, nec consectetur nibh sapien et justo. Curabitur bibendum neque eu facilisis porta. Aliquam sed rhoncus nulla. Nullam quis mollis enim. Aenean in est rhoncus, rutrum odio quis, ultricies sapien. Morbi ac quam sed sem semper vehicula. Sed quis malesuada quam. Phasellus bibendum nisi eu sem accumsan, eget interdum neque gravida. Nulla gravida arcu non nulla sagittis auctor. Vestibulum rutrum pulvinar lacus, id ullamcorper augue suscipit nec. Donec ultrices fermentum auctor. Maecenas a pulvinar dolor. Sed lacinia est a pulvinar rhoncus.",
  "Aliquam iaculis erat quis lacus placerat ultrices. Vestibulum blandit magna in elit accumsan tincidunt. Ut tempor nulla metus, ut sagittis mauris porttitor quis. Curabitur feugiat dui in commodo interdum. Aenean posuere, nulla id suscipit molestie, nisi lectus lobortis neque, vitae rutrum nunc urna sit amet est. Praesent suscipit congue efficitur. Etiam vel interdum erat, sit amet tempus nunc. Donec molestie, neque vitae tincidunt elementum, erat lorem suscipit diam, quis efficitur elit orci non turpis. In ac venenatis tortor. Vestibulum tempor volutpat velit et interdum. Suspendisse nec varius dolor. Sed sed elit est. Cras laoreet mauris nec suscipit congue. Etiam non convallis tellus. In quis nibh vulputate, volutpat ligula quis, condimentum nibh. Donec aliquam feugiat lacus, vestibulum posuere ipsum lobortis ultricies.",
  "In dui quam, pretium et nibh et, fermentum rhoncus tortor. Donec pharetra ultrices nibh vel semper. In felis massa, bibendum eu gravida id, accumsan ornare ligula. Proin blandit purus id suscipit efficitur. Quisque molestie arcu ut ligula aliquam, sed cursus erat pulvinar. Sed quis ligula tempor, ultrices libero in, congue turpis. Fusce aliquet ante quis vehicula gravida. Ut sapien turpis, scelerisque sit amet laoreet sit amet, tempor ac neque. Quisque pellentesque sem non ipsum placerat feugiat. Aenean ultricies turpis ante, sed sodales nunc posuere sit amet. Morbi volutpat est in nulla aliquet, vitae cursus sem faucibus. Nunc consectetur, lorem in egestas venenatis, nibh nisi posuere augue, in lacinia turpis enim eu ligula.",
  "Vestibulum ornare feugiat condimentum. Morbi imperdiet nulla purus, eu lobortis ante finibus at. Nunc molestie lorem in dui euismod hendrerit. Vestibulum mattis dignissim interdum. Morbi ac semper turpis, quis rhoncus sem. Pellentesque gravida, tellus hendrerit semper tempor, lorem nunc tempus elit, vitae posuere massa orci a leo. Quisque vestibulum leo vel augue semper gravida.",
  "Maecenas nec dolor a nisi interdum convallis eu in neque. Curabitur pulvinar enim non commodo consectetur. Morbi nunc mi, fermentum congue ipsum in, ultrices maximus magna. Quisque ultricies sem lectus, ut tincidunt eros vestibulum pulvinar. Mauris non tincidunt nunc. Morbi vestibulum, nisl sed lobortis eleifend, ex orci congue ipsum, vitae suscipit est est sed mi. In at orci at arcu auctor condimentum. Etiam vel tellus nec ex interdum eleifend sit amet ac sapien. Etiam ac egestas velit.",
  "Nunc malesuada laoreet pharetra. Aenean at ex ut metus varius fermentum a vitae dui. Etiam dictum, lorem at fermentum imperdiet, mauris ipsum posuere elit, vel auctor mi erat vitae magna. Quisque tincidunt nisi ac semper molestie. Aliquam placerat turpis justo, at congue arcu sodales non. Donec efficitur magna sed nisl suscipit gravida. Quisque sodales arcu neque, vitae tincidunt orci porttitor sed. Pellentesque eu ex quis enim consectetur pharetra. Proin mollis pretium purus id pretium. Quisque ut enim ut diam finibus rhoncus at sit amet ipsum. Morbi ultrices justo in volutpat luctus. Nunc mattis lorem ac velit ultricies, sit amet dictum ipsum rhoncus. Quisque consequat convallis nulla, et dictum libero bibendum ut."
]

document.querySelector(".create").addEventListener("click",function(){

  let paragrafNumber = document.querySelector(".paragrafNumber").value;
  let test = document.querySelector(".test")
  test.innerHTML=""
  let hazirMetinler = []

  for(let i=0;i<paragrafNumber;i++){
    let rndIndex = Math.floor(Math.random()*metinler.length);
    let rndParagraf = metinler[rndIndex];
    hazirMetinler.push(rndParagraf);
    metinler.splice(rndIndex,1);
  }

  hazirMetinler.forEach(element => {
    let myP = document.createElement("p");
    myP.innerHTML=element;
    test.append(myP)
  });
  
})

// let x = 3;

// fetch(`http://metaphorpsum.com/paragraphs/${x}/5`)
// .then(res => res.text())
// .then(results => {
//   console.log(results)
// })
 